version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  bot:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env.bot

volumes:
  pg_data: